### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage

### ISSUE THREAD

**Issue by expipiplus1** [nomeata/ghc-justdoit#4]
It's possible that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please? Note that this requires cabal-install >= 1.24

Thanks!

**Comment by nomeata** [comment]
Thanks, done. Although the documentation is kinda embarrassing sparse…

**Comment by expipiplus1** [comment]
Thanks!
